# This file describes an application. You can have multiple applications
# in the same project.
#
# See https://docs.platform.sh/user_guide/reference/platform-app-yaml.html

# The name of this app. Must be unique within a project.
name: ndadrop

# The runtime the application uses.
type: nodejs:20


# The configuration of app when it is exposed to the web.
web:
  commands:
   start: "npm install & node index.js"

# The size of the persistent disk of the application (in MB).
disk: 512

mounts:
    'run':
        source: local
        source_path: run

source:
  operations:
    auto-update:
      command: |
        curl -fsS https://raw.githubusercontent.com/platformsh/source-operations/main/setup.sh | { bash /dev/fd/3 sop-autoupdate; } 3<&0
    
